export const POKEMONS_LOADING = 'POKEMONS_LOADING';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_ERROR = 'GET_POKEMONS_ERROR';
export const GET_SINGLE_POKEMON_LOADING = 'GET_SINGLE_POKEMON_LOADING';
export const GET_SINGLE_POKEMON_SUCCESS = 'GET_SINGLE_POKEMON_SUCCESS';
export const GET_SINGLE_POKEMON_ERROR = 'GET_SINGLE_POKEMON_ERROR';
export const FILTER_TYPE = 'FILTER_TYPE';
